// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kplhoobhnumsqgttudak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwbGhvb2JobnVtc3FndHR1ZGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjMwMzgsImV4cCI6MjA2NzQ5OTAzOH0.a4Cct9OY2KkTvxsFlG-aOv5GADWQSpr8cH108E1P8Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});